version: 2
updates:

  - package-ecosystem: nuget
    directory: "/src/cert-manager-acme-httphook"
    schedule:
      interval: "daily"
  - package-ecosystem: docker
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "friday"
#  - package-ecosystem: "github-actions"
#    # Workflow files stored in the
#    # default location of `.github/workflows`
#    directory: "/"
#    schedule:
#      interval: "daily"